# Generated by Django 5.1.2 on 2025-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
        ),
    ]
