# Generated by Django 5.1.2 on 2025-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='emoji',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
