# Generated by Django 5.1.2 on 2025-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogsection_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandesUtiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField(verbose_name='Contenu')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(blank=True, max_length=50)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
        ),
    ]
