# Generated by Django 5.1.2 on 2025-05-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_commandesutiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandesUtiles',
            new_name='CommandeUtile',
        ),
    ]
