# Generated by Django 5.1.2 on 2025-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_commandesutiles_commandeutile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=50, verbose_name='Emoji (FontAwesome ou Unicode)')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (facultative)')),
                ('commande', models.CharField(max_length=255, verbose_name='Commande')),
            ],
        ),
        migrations.AddField(
            model_name='commandeutile',
            name='commandes',
            field=models.ManyToManyField(blank=True, related_name='sections', to='Blog.commande', verbose_name='Commandes associées'),
        ),
    ]
