# Generated by Django 5.1.2 on 2025-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_commande_commandeutile_commandes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='titre',
            new_name='title',
        ),
        migrations.AddField(
            model_name='commande',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
