# Generated by Django 5.1.2 on 2025-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_titre_commande_title_commande_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
