# Generated by Django 5.1.2 on 2025-05-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_commande_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeutile',
            name='content',
        ),
    ]
