# Generated by Django 5.1.2 on 2026-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_commandeutile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande',
            field=models.TextField(max_length=255, verbose_name='Commande'),
        ),
    ]
