# Generated by Django 5.1.2 on 2026-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_commande_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande',
            field=models.TextField(verbose_name='Commande'),
        ),
    ]
