# Generated by Django 5.1.2 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_commande_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(verbose_name='Contenu')),
            ],
        ),
    ]
