# Generated by Django 5.1.2 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_tutoriel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
