# Generated by Django 5.1.2 on 2026-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_tutoriel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeutile',
            name='commandes',
        ),
        migrations.RemoveField(
            model_name='commandeutile',
            name='emoji',
        ),
        migrations.AddField(
            model_name='commandeutile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='tutoriel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
