# Generated by Django 5.1.2 on 2024-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=255, verbose_name='Poste')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project_description', models.TextField(blank=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
    ]
