# Generated by Django 5.1.2 on 2024-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entreprise'),
        ),
    ]
