# Generated by Django 5.1.2 on 2024-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experiences_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
