# Generated by Django 5.1.2 on 2024-11-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_experiences_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
