# Generated by Django 5.1.2 on 2024-11-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_experiences_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='experiences',
            new_name='Experience',
        ),
    ]
