# Generated by Django 5.1.2 on 2024-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_experiences_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='project_description',
        ),
        migrations.AddField(
            model_name='experience',
            name='projects',
            field=models.TextField(blank=True, null=True, verbose_name='Projets'),
        ),
    ]
