# Generated by Django 5.1.2 on 2024-11-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_project_remove_experience_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='projects',
        ),
        migrations.AddField(
            model_name='experience',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
