# Generated by Django 5.1.2 on 2024-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_experience_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('tasks', models.TextField(verbose_name='Taches')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='projects',
            field=models.ManyToManyField(blank=True, to='cv.project', verbose_name='Projets'),
        ),
    ]
