# Generated by Django 5.1.2 on 2024-11-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_project_experience_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='project_description',
        ),
    ]
