# Generated by Django 5.1.2 on 2024-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_experience_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('certification', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-start_date'],
            },
        ),
    ]
