# Generated by Django 5.1.2 on 2024-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-year'], 'verbose_name': 'Formation'},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='formation',
            name='year',
            field=models.IntegerField(blank=True, default=2024, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='certification',
            field=models.BooleanField(default=False, verbose_name='Certification'),
        ),
    ]
