# Generated by Django 5.1.2 on 2024-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_formation_options_remove_formation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Année'),
        ),
    ]
