# Generated by Django 5.1.2 on 2024-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_alter_formation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution'),
        ),
    ]
