# Generated by Django 5.1.2 on 2024-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_formation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
