# Generated by Django 5.1.2 on 2024-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_formation_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(verbose_name='Contenu')),
            ],
        ),
    ]
