# Generated by Django 5.1.2 on 2024-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='identifier',
            field=models.IntegerField(default=999, verbose_name='Identifiant'),
        ),
    ]
