# Generated by Django 5.1.2 on 2025-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_competence_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien'),
        ),
    ]
