# Generated by Django 5.1.2 on 2025-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_blogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
