# Generated by Django 5.1.2 on 2025-05-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_blogsection_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSection',
        ),
    ]
