# Generated by Django 5.1.2 on 2025-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_delete_blogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
