# Generated by Django 5.1.2 on 2026-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_experience_icon_name_formation_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, help_text='Ex: fas fa-gears', max_length=50, null=True, verbose_name='Icône'),
        ),
    ]
