# Generated by Django 5.1.2 on 2026-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
