# Generated by Django 5.1.2 on 2026-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier CV (PDF)')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
            },
        ),
    ]
