# Generated by Django 5.1.2 on 2026-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre (ex: Ingénieur Systèmes...)')),
                ('sous_titre', models.CharField(max_length=200, verbose_name='Sous-titre (ex: Fiabilité, Résilience...)')),
                ('presentation', models.TextField(verbose_name='Texte de présentation')),
                ('photo', models.ImageField(upload_to='hero/', verbose_name='Photo de profil')),
            ],
            options={
                'verbose_name': 'Section Hero',
            },
        ),
    ]
