# Generated by Django 5.1.2 on 2026-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphe_1', models.TextField(verbose_name='Paragraphe 1')),
                ('paragraphe_2', models.TextField(blank=True, null=True, verbose_name='Paragraphe 2')),
                ('paragraphe_3', models.TextField(blank=True, null=True, verbose_name='Paragraphe 3')),
            ],
            options={
                'verbose_name': 'Section À propos',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('niveau', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Niveau (1 à 5)')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordering'],
            },
        ),
    ]
