# Generated by Django 5.1.2 on 2026-03-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoisirCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='fa-solid fa-star', help_text='Ex: fa-solid fa-gamepad', max_length=100, verbose_name='Icône FontAwesome')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de loisir',
                'verbose_name_plural': 'Catégories de loisirs',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='LoisirItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loisirs/', verbose_name='Image')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loisirs.loisircategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Item de loisir',
                'verbose_name_plural': 'Items de loisirs',
                'ordering': ['ordering'],
            },
        ),
    ]
