# Generated by Django 5.1.2 on 2026-03-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loisirs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loisircategorie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='loisiritem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
